version: 0.2
os: linux
files:
  - source: .
    destination: /home/ubuntu/app
permissions:
  - object: /home/ubuntu/app
    owner: ubuntu
    group: ubuntu
    mode: 755
hooks:
  BeforeInstall:
    - location: scripts/npm_install.sh
      timeout: 300
      runas: ubuntu
  AfterInstall:
    - location: scripts/restart.sh
      timeout: 300
      runas: ubuntu
