version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - npm install -g @nestjs/cli
      - npm install
  build:
    commands:
      - nest build
  post_build:
    commands:
      - echo "Packaging artifacts..."
      - zip -r build_output.zip dist package*.json
artifacts:
  files:
    - build_output.zip