version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Installing dependencies..."
      - npm install
  pre_build:
    commands:
      - echo "Running tests..."
      - npm run test
  build:
    commands:
      - echo "Building the application..."
      - npm run build
  post_build:
    commands:
      - echo "Packaging build artifacts..."
      - zip -r build_output.zip dist package.json package-lock.json
artifacts:
  files:
    - build_output.zip
