version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - export NODE_ENV=development
      - npm install -g @nestjs/cli
      - npm install
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - echo "Packaging artifacts..."
      - chmod +x scripts/restart.sh
      - zip -r build_output.zip appspec.yml dist/ package*.json scripts/
      - echo "Uploading artifact to S3..."
      - aws s3 cp build_output.zip s3://seenyor-backend-2-pipeline-bucket/build_output/build_output.zip

artifacts:
  files:
    - appspec.yml
    - scripts/**
    - dist/**
    - package*.json
  discard-paths: no

