version: 0.2
phases:
  install:
    commands:
      - echo "Installing Node.js and dependencies..."
      - npm install -g @nestjs/cli  # <-- Add this line
      - npm install
  build:
    commands:
      - echo "Building the application..."
      - nest build  # Now works because CLI is installed
  post_build:
    commands:
      - echo "Packaging build artifacts..."
      - zip -r build_output.zip dist package.json package-lock.json
artifacts:
  files:
    - build_output.zip