version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "Setting environment variables..."
      - export NODE_ENV=production
      - echo "Installing dependencies..."
      - npm install -g @nestjs/cli
      - npm install
      - npm install --save-dev @types/node  # ✅ Ensure @types/node is installed
  build:
    commands:
      - echo "Verifying installed TypeScript types..."
      - ls -lah node_modules/@types/node  # ✅ Debug step
      - cat tsconfig.json  # ✅ Debug step
      - echo "Building the application..."
      - npm run build
  post_build:
    commands:
      - echo "Packaging artifacts..."
      - chmod +x scripts/restart.sh
      - zip -r build_output.zip dist package*.json appspec.yml scripts/
      - echo "Uploading artifact to S3..."
      - aws s3 cp build_output.zip s3://seenyor-backend-1-pipeline-bucket/build_output/build_output.zip

artifacts:
  files:
    - build_output.zip
