version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - export NODE_ENV=development
      - npm install -g @nestjs/cli
      - npm install
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - echo "Packaging artifacts..."
      - zip -r build_output.zip dist package*.json

artifacts:
  files:
    - '**/*'
  base-directory: 'dist'