version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - export NODE_ENV=development
      - npm install -g @nestjs/cli
      - npm install
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - echo "Packaging artifacts..."
      - zip -r build_output.zip dist package*.json
      # (Optional) Explicitly copy the zip to a known S3 key:
      - echo "Uploading artifact to S3 with fixed key..."
      - aws s3 cp build_output.zip s3://seenyor-backend-1/build_outp/build_output.zip


artifacts:
  files:
    - build_output.zip
