version: '3.8'

services:
  Auth-DB:
    image: postgres:13
    container_name: ${CONTAINER_NAME}
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - '${DATABASE_PORT}:5432'
    env_file:
      - .env
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app-network

  redis:
    image: redis:alpine
    container_name: ${REDIS_CONTAINER_NAME}
    ports:
      - '${REDIS_PORT}:6379'
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
    env_file:
      - .env
    restart: always
    networks:
      - app-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: business-automation-app
    depends_on:
      - Auth-DB
      - redis
    env_file:
      - .env
    ports:
      - "80:3000"
    restart: always
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
